Convert incoming array params to destination field type
In `/v0/ingest/localToGW`--and likely other endpoints for operations using
primitive array parameters--unconverted assignment throws this error:

```
java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field mil.nga.giat.geowave.core.ingest.local.LocalInputCommandLineOptions.extensions to [Ljava.lang.Object;
``` (+2 squashed commits)
Squashed commits:
[6ca6f1109b0] Improve error logging
[b8b89970a7e] Add null checks for missing/optional params